# Generated by Django 4.2.6 on 2023-10-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='name',
        ),
        migrations.AddField(
            model_name='home',
            name='small_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='home',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='home',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
