# Generated by Django 4.2.6 on 2023-10-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_home_name_home_small_title_home_sub_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='small_title',
        ),
        migrations.RemoveField(
            model_name='home',
            name='sub_title',
        ),
        migrations.AddField(
            model_name='home',
            name='banner',
            field=models.ImageField(default=5, upload_to='media/banner/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
