# Generated by Django 4.2.6 on 2023-10-31 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_portfolio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
